# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ramteja tadishetti 
email: ramtejatadishetti<at>gmail<dot>com
description: Will fill this up someday
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: its_ramteja
github_username:  ramtejatadishetti
linkedin_username: in/tramteja
theme-dark: true #Set to true to change to dark website theme

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
